FROM node:14 as build-stage
RUN apt-get update && apt-get install git
RUN git clone https://alexortner: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@github.com/ThinkportRepo/big-data-on-k8s-workshop.git
WORKDIR /app
COPY frontend/package*.json ./
RUN npm install
COPY frontend/ .

RUN npm run build

FROM nginx as production-stage
RUN apt-get update && apt-get install git -y
RUN mkdir /app
COPY --from=build-stage /app/dist /app
COPY docker/nginx.frontend.conf /etc/nginx/nginx.conf


# Overriding the default NGINX container behavior
COPY docker/substitute_environment_variables.frontend.sh /substitute_environment_variables.sh
RUN chmod +x /substitute_environment_variables.sh

ENTRYPOINT ["/substitute_environment_variables.sh"]