apiVersion: v1
kind: Service
metadata:
  name: sqlpad
  namespace: {{.Values.namespace}}
spec:
  ports:
    - name: sqlpad
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: sqlpad
