apiVersion: v1
kind: Pod
metadata:
  name: mypod
  namespace: default
spec:
  containers:
    - name: linux
      image: alpine:3.17
      command:
        - sh
        - "-c"
        - |
          apk add --no-cache curl;
          echo "Schaun wir mal ob wir den Service auf die Dashboard Website erreichen?";
          echo "##############################################";
          curl http://dashboard.frontend.svc.cluster.local:8081;
          echo "";
          echo "##############################################";
          echo "The End";
