{{- if .Values.ingress.create }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  #annotations:
  #  kubernetes.io/ingress.class: addon-http-application-routing
  name: controlcenter
  namespace: {{.Values.namespace}}
spec:
  rules:
    - host: {{.Values.ingress.subdomain}}.{{.Values.ingress.host}}
      http:
        paths:
          - backend:
              service:
                name: controlcenter
                port:
                  number: 9021
            path: /
            pathType: Prefix
{{- end -}}