apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "pyspark-notebook.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
    nginx.ingress.kubernetes.io/app-root: /jupyter
  labels:
    "app.kubernetes.io/name": {{ template "pyspark-notebook.name" . }}
    "helm.sh/chart": {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    "app.kubernetes.io/managed-by": {{ .Release.Service }}
    "app.kubernetes.io/instance": {{ .Release.Name }}
    "app.kubernetes.io/version": {{ .Chart.AppVersion }}
spec:
  rules:
    - host: {{.Values.host}}
      http:
        paths:
          - backend:
              service:
                name: {{ template "pyspark-notebook.jupyter.service.name" . }}
                port:
                  number: {{ .Values.jupyter.externalPort }}
            path: /
            pathType: Prefix
