apiVersion: v1
kind: Pod
metadata:
  name: admin
  namespace: frontend
spec:
  containers:
    - name: admin
      image: "thinkportgmbh/workshops:terminal"
      imagePullPolicy: Always
      command:
        - "sh"
        - "-c"
        - "sleep 3000"
      ports:
        - containerPort: 8080
      securityContext:
        privileged: true
      volumeMounts:
        - name: workshop
          mountPath: /workshop
        - name: kube-config
          mountPath: /home/coder/downloads/kube_config
  volumes:
    - name: workshop
      persistentVolumeClaim:
        claimName: workshop
    - name: kube-config
      secret:
        secretName: kube-config
        defaultMode: 0600
