apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workshop
  namespace: frontend
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 20Gi
