apiVersion: v1
kind: Pod
metadata:
  name: twitter-data-producer
  namespace: kafka
spec:
  containers:
    - name: python
      image: thinkportgmbh/workshops:twitter-data-producer
      imagePullPolicy: Always
      env:
        - name: KAFKA_SERVER
          value: "kafka.kafka.svc.cluster.local:9092"
        - name: KAFKA_TOPIC
          value: "twitter-raw"
      command:
        - sh
        - "-c"
        - |
          echo "##############################################";
          echo $KAFKA_SERVER;
          echo $KAFKA_TOPIC;
          python3 twitter_data_producer.py;
