apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: simple-app
  namespace: spark
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: "thinkportgmbh/workshops:spark-3.3.1"
  imagePullPolicy: IfNotPresent # or Always
  # Python Script/Java Jar that should be submitted
  mainApplicationFile: 
  sparkVersion: "3.3.1"
  # extra Spark configurations
  sparkConf:
    "spark.serializer": "org.apache.spark.serializer.KryoSerializer"
  # s3 connection configuration
  hadoopConf:
    "fs.s3a.endpoint":
    "fs.s3a.access.key": 
    "fs.s3a.secret.key": 
    "fs.s3a.path.style.access": "true"
    "fs.s3.impl": "org.apache.hadoop.fs.s3a.S3AFileSystem"
    "fs.s3a.aws.credentials.provider": "org.apache.hadoop.fs.s3a.SimpleAWSCredentialsProvider"
    "fs.s3a.connection.ssl.enabled": "false"
  # driver pod configuration
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.3.1
    serviceAccount: spark
  # executor pod configuration
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 3.3.1
