{
 "title": "Overview",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~\"spark|frontend|kafka|trino\"},namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=\"$namespace\"},pod)"
    }
   }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 }, "options": { "content": "# Cluster Summary\n" } },
  {
   "title": "Nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(count by (node) (kube_node_info))"
    }
   ]
  },
  {
   "title": "Namespaces",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "count(kube_namespace_created)" }
   ]
  },
  {
   "title": "Running Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\"})"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 }, "options": { "content": "# Spark Summary\n" } },
  {
   "title": "Spark Driver",
   "type": "stat",
   "description": "Count over all registered Spark Drivers",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_labels{label_spark_role=\"driver\"} or kube_pod_labels{label_app_kubernetes_io_component=\"jupyter\"})"
    }
   ]
  },
  {
   "title": "Spark Executors",
   "type": "stat",
   "description": "Count over all running Executor Pods",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_labels{label_spark_role=\"executor\"})"
    }
   ]
  },
  {
   "title": "Spark Operator Apps",
   "type": "stat",
   "description": "Spark apps managed from Spark Operator",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "spark_app_running_count" }
   ]
  },
  { "type": "text", "gridPos": { "h": 3, "w": 24, "x": 0, "y": 3 }, "options": { "content": "# Global Resource Usage" } },
  {
   "title": "CPU Usage (absolut)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(1-rate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval]))",
     "legendFormat": "Real"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\"})",
     "legendFormat": "Limits"
    },
    { "expr": "sum(machine_cpu_cores)", "legendFormat": "Total" }
   ]
  },
  {
   "title": "RAM Usage (absolut)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes)",
     "legendFormat": "Real"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\"})",
     "legendFormat": "Limits"
    },
    { "expr": "sum(machine_memory_bytes)", "legendFormat": "Total" }
   ]
  },
  {
   "title": "CPU Usage (relative)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(1-rate(node_cpu_seconds_total{mode=\"idle\"}[$__rate_interval]))",
     "legendFormat": "Real"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\"}) / sum(machine_cpu_cores)",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\"}) / sum(machine_cpu_cores)",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "RAM Usage (relative)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / sum(node_memory_MemTotal_bytes)",
     "legendFormat": "Real"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\"}) / sum(machine_memory_bytes)",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\"}) / sum(machine_memory_bytes)",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "CPU utilization by namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\",namespace=~\"spark|frontend|kafka|trino\"}[$__rate_interval])) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM utilization by namespace",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{image!=\"\",namespace=~\"spark|frontend|kafka|trino\"}) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 26 },
   "options": {
    "content": "# Spark Resource Usage\n\nDiese Metriken filtern nur auf die Jupyter Driver und Executor Pods im Namespace Frontend. \nACHTUNG!! Der Chart zeigt die gesamte Historie an, also auch Executor Pods die bereits nicht mehr laufen aus den vorherigen Aufgaben"
   }
  },
  {
   "title": "CPU utilization by Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\"frontend\", image!=\"\",container=~\"jupyter|spark-kubernetes-executor\"}[$__rate_interval])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM utilization by Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(container_memory_usage_bytes{image!=\"\",namespace=~\"frontend\",container=~\"jupyter|spark-kubernetes-executor\"}[$__rate_interval])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "ProcessTreeJVMVMemory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(metrics_executor_ProcessTreeJVMVMemory_bytes{namespace=\"frontend\"}[$__rate_interval])",
     "legendFormat": "{{application_name}}_{{executor_id}}"
    }
   ]
  },
  {
   "title": "JVMHeapMemory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(metrics_executor_JVMHeapMemory_bytes{namespace=~\"frontend\"}[$__rate_interval])",
     "legendFormat": "{{application_name}}_{{executor_id}}"
    }
   ]
  },
  {
   "title": "OnHeapExecutionMemory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(metrics_executor_OnHeapExecutionMemory_bytes{namespace=\"frontend\"}[$__rate_interval])",
     "legendFormat": "{{application_name}}_{{executor_id}}"
    }
   ]
  },
  {
   "title": "OnHeapStorageMemory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(metrics_executor_OnHeapStorageMemory_bytes{namespace=\"frontend\"}[$__rate_interval])",
     "legendFormat": "{{application_name}}_{{executor_id}}"
    }
   ]
  },
  {
   "title": "OnHeap Execution Memory",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "metrics_executor_OnHeapExecutionMemory_bytes{namespace=\"frontend\"}",
     "legendFormat": "{{application_name}}_{{executor_id}}"
    }
   ]
  },
  {
   "title": "OnHeap Storage Memory",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "metrics_executor_OnHeapStorageMemory_bytes{namespace=\"frontend\"}",
     "legendFormat": "{{application_name}}_{{executor_id}}"
    }
   ]
  },
  {
   "title": "Shuffle Read",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(metrics_executor_totalShuffleRead_bytes_total{namespace=\"frontend\"}[$__rate_interval])",
     "legendFormat": "shuffle_read_{{executor_id}}"
    }
   ]
  },
  {
   "title": "Shuffle Write",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(metrics_executor_totalShuffleWrite_bytes_total{namespace=\"frontend\"}[$__rate_interval])",
     "legendFormat": "shuffle_write_{{executor_id}}"
    }
   ]
  }
 ]
}