apiVersion: apps/v1
kind: Deployment
metadata:
  name: vscode
  namespace: "{{ .Values.namespace }}"
spec:
  selector:
    matchLabels:
      app: vscode
  replicas: 1
  template:
    metadata:
      labels:
        app: vscode
    spec:
      serviceAccountName: vscode
      automountServiceAccountToken: true
      containers:
        - name: vscode
          image: "{{ .Values.image }}"
          ports:
            - containerPort: 8080
              name: vscode
          securityContext:
            privileged: true
          env:
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vscode
                  key: password
          resources:
            limits:
              memory: 1Gi
            requests:
              memory: 1Gi
          volumeMounts:
            - name: git
              mountPath: /home/coder/project
      initContainers:
        - name: git-cloner
          image: alpine/git:latest
          args:
            - clone
            - https://github.com/ThinkportRepo/big-data-on-k8s-workshop.git
            - /workshop
          volumeMounts:
            - mountPath: /workshop
              name: git
      volumes:
        - name: git
          emptyDir: {}
