apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: simple-app-hist
  namespace: spark
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: "thinkportgmbh/workshops:spark-3.3.1"
  imagePullPolicy: IfNotPresent # or Always
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: spark-history-server
  # Python Script/Java Jar that should be submitted
  mainClass: org.apache.spark.examples.SparkPi
  mainApplicationFile: "local:///opt/spark/examples/src/main/python/pi.py"
  sparkVersion: "3.3.1"
  # extra Spark configurations
  sparkConf:
    "spark.serializer": "org.apache.spark.serializer.KryoSerializer"
    "spark.driver.extraJavaOptions": "-Divy.cache.dir=/tmp -Divy.home=/tmp"
    "spark.eventLog.enabled": "true"
    "spark.eventLog.dir": "file:/tmp/spark-events"
  # driver pod configuration
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.3.1
    serviceAccount: spark
    volumeMounts:
      - name: data
        # default path the spark history server looks for logs
        mountPath: /tmp/spark-events
  # executor pod configuration
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 3.3.1
    volumeMounts:
      - name: data
        # default path the spark history server looks for logs
        mountPath: /tmp/spark-events
  monitoring:
    exposeDriverMetrics: true
    exposeExecutorMetrics: true
