apiVersion: apps/v1
kind: Deployment
metadata:
  name: twitter-data-producer
  namespace: kafka
  labels:
    app: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
        - name: producer
          image: thinkportgmbh/workshops:twitter-data-producer
          imagePullPolicy: Always
          env:
            - name: KAFKA_SERVER
              value: "kafka.kafka.svc.cluster.local:9092"
            - name: KAFKA_TOPIC
              value: "twitter-raw"
          command:
            - sh
            - "-c"
            - |
              echo "##############################################";
              echo $KAFKA_SERVER;
              echo $KAFKA_TOPIC;
              python3 twitter_data_producer.py;
