FROM confluentinc/cp-server-connect-base:7.3.0

RUN confluent-hub install --no-prompt jcustenborder/kafka-connect-twitter:0.3.34
RUN confluent-hub install --no-prompt confluentinc/kafka-connect-s3:10.3.0
RUN confluent-hub install --no-prompt confluentinc/kafka-connect-cassandra:latest
