# PVC for all Frontend apps to share code base
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workshop
  namespace: frontend
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 20Gi
---
# PVC for Spark applications and Spark History Server
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spark-history-server
  namespace: spark
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 10Gi
