apiVersion: v1
kind: Pod
metadata:
  name: admin
  namespace: frontend
spec:
  #serviceAccountName: kubectl
  containers:
    - name: main
      image: alpine:3.17
      command:
        - sh
        - "-c"
        - |
          apk add --no-cache curl;
          sleep 3000
