apiVersion: apps/v1
kind: Deployment
metadata:
  name: twitter-data-converter
  namespace: kafka
  labels:
    app: converter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: converter
  template:
    metadata:
      labels:
        app: converter
    spec:
      containers:
        - name: python
          image: thinkportgmbh/workshops:twitter-data-converter
          imagePullPolicy: Always
          command:
            - sh
            - "-c"
            - |
              echo "##############################################";
              echo $KAFKA_SERVER;
              echo $KAFKA_SOURCE_TOPIC;
              echo $KAFKA_TARGET_TOPIC;
              python3 twitter_data_converter.py;
          env:
            - name: KAFKA_SERVER
              value: "kafka.kafka.svc.cluster.local:9092"
            - name: KAFKA_SOURCE_TOPIC
              value: "twitter-raw"
            - name: KAFKA_TARGET_TOPIC
              value: "twitter-table"
