apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: spark-operator-monitor
  namespace: spark
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: spark-operator
  endpoints:
    - port: metrics
