apiVersion: v1
kind: Service
metadata:
  # Service to expose metric port from Spark Operator
  name: service-monitor-operator
  labels:
    app: spark-operator
  namespace: spark
spec:
  ports:
    - name: metrics
      port: 8090
      targetPort: 10254
      protocol: TCP
  selector:
    app.kubernetes.io/name: spark-operator
