apiVersion: v1
kind: Service
metadata:
  # Service to expose metric port from Spark Operator
  name: spark-driver-service
  labels:
    app: spark-driver
  namespace: spark
spec:
  ports:
    - name: metrics
      port: 4040
      targetPort: 4040
      protocol: TCP
  selector:
    spark-role: driver
