# Default Values

# Kubernetes namespace
namespace: "frontend"

# Image
image: "thinkportgmbh/workshops:vscode"

# Basic Authentication Username
user: "trainadm"
# Basic Authentication Password
password: "train@thinkport"

# IP whitelist
loadBalancerSourceRanges: []

# Ingress Hostname
host: vscode.a14e3323952046c3bc3f.eastus.aksapp.io
