apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vscode
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
    - host: {{.Values.host}}
      http:
        paths:
          - backend:
              service:
                name: vscode
                port:
                  number: 80
            path: /
            pathType: Prefix
