apiVersion: v1
kind: Pod
metadata:
  name: twitter-stream-converter
  namespace: kafka
spec:
  containers:
    - name: python
      image: thinkportgmbh/workshops:twitter-data-converter
      imagePullPolicy: Always
      env:
        - name: KAFKA_SERVER
          value: "kafka-cp-kafka.kafka.svc.cluster.local:9092"
        - name: KAFKA_SOURCE_TOPIC
          value: "twitter-raw"
        - name: KAFKA_TARGET_TOPIC
          value: "twitter-table"
      command:
        - sh
        - "-c"
        - |
          echo "##############################################";
          echo $KAFKA_SERVER;
          echo $KAFKA_SOURCE_TOPIC;
          echo $KAFKA_TARGET_TOPIC;
          python3 twitter_data_converter.py;
